apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-platform-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/naman833/cloud-platform-bootstrap
    targetRevision: main
    path: k8s/overlays/test
  destination:
    server: https://kubernetes.default.svc
    namespace: cloud-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
