apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-platform

resources:
  - ../../base

patches:
  - path: patch-replicas.yaml

images:
  - name: cloud-platform-app
    newName: REPLACE_WITH_ECR_URI
    newTag: latest
